version: '3.8'
services:

  azure-terraform:
    image: 'azureterraform:latest'
    container_name: azure-terraform
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: azure
    stdin_open: true
    tty: true
    working_dir: /src
    environment:
      - ARM_SUBSCRIPTION_ID
      - ARM_TENANT_ID
      - ARM_CLIENT_ID
      - ARM_CLIENT_SECRET
      - ARM_ACCESS_KEY
      - TF_VAR_resource_group_name
      - TF_VAR_service_principal_name
